Repository lumapps/lumapps-extensions-templates, pull requests merged in 2020-11, with the labels that each got.

#19 Doc update
  .gitignore
  CONTRIBUTING.md
  NOTES.md
  docs/.nojekyll
  docs/README.md
  docs/_config.yml
  docs/_sidebar.md
  docs/index.html
  docs/index.md
  package.json
  yarn.lock
Labels: documentation

#23 chore(pr): PR template proposal for partner extension
  template-react-ts/.github/pull_request_template.md
  template-react/.github/pull_request_template.md
Labels: enhancement

#22 chore(eslint): add eslint configuration
  template-react-ts/.eslintrc.json
  template-react-ts/package.json
Labels: enhancement

#21 feat(config): update config files for extensions
  template-react-ts/src/config.js
  template-react/package.json
  template-react/src/config.js
Labels: bug, enhancement
